# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cvbuilder-it

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ace77fcf41184b27aa2b62840b2829a8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4118ef0a8dd94203bdbe65b74bbc9411 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_ace77fcf41184b27aa2b62840b2829a8 }}/sominola/cv.ithoot.backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cvbuilder-it'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b637568f097242949ea260d1b25ed576 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_ace77fcf41184b27aa2b62840b2829a8 }}/sominola/cv.ithoot.backend:${{ github.sha }}'